export const SAMPLE_PRODUCTS = [
    {
        id: "p1",
        title: "Ray-Ban Round Metal",
        slug: "ray-ban-round-metal",
        price: 169.0,
        gender: "unisex",
        category: "Sunglasses",
        material: "metal",
        color: "gold",
        popularity: 98,
        createdAt: "2025-09-01",
        images: [
            "https://images.unsplash.com/photo-1598257003316-07b8ce0e655a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1581349487947-3e7a802a046b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1581363769522-5f9a68b5eafd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        ],
        description:
            "Iconic round metal sunglasses with G-15 green lenses. Perfect blend of vintage and modern style.",
        features: [
            "Classic round design",
            "100% UV protection",
            "Adjustable nose pads",
            "Premium metal frame",
        ],
    },
    {
        id: "p2",
        title: "Oakley Wingspan",
        slug: "oakley-wingspan",
        price: 199.0,
        gender: "men",
        category: "Sports Glasses",
        material: "titanium",
        color: "black",
        popularity: 95,
        createdAt: "2025-08-15",
        images: [
            "https://images.unsplash.com/photo-1508898578281-774ac4893a21?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1560717844-12a5bd398cec?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1563225400-113f66fa2b8c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        ],
        description:
            "High-performance sports glasses with advanced lens technology for ultimate clarity and protection.",
        features: [
            "Impact-resistant lenses",
            "Hydrophobic coating",
            "Enhanced peripheral vision",
            "Lightweight design",
        ],
    },
    {
        id: "p3",
        title: "Tom Ford Morgan",
        slug: "tom-ford-morgan",
        price: 329.0,
        gender: "women",
        category: "Prescription Glasses",
        material: "acetate",
        color: "tortoise",
        popularity: 92,
        createdAt: "2025-09-10",
        images: [
            "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1587595439204-c760f4055e17?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1529253355930-95f34a2a86f8?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        ],
        description:
            "Elegant cat-eye frames crafted from premium Italian acetate. Timeless sophistication meets modern luxury.",
        features: [
            "Italian acetate frame",
            "Gold-plated temples",
            "Anti-reflective coating",
            "Spring hinges",
        ],
    },
    {
        id: "p4",
        title: "Persol 649 Original",
        slug: "persol-649-original",
        price: 279.0,
        gender: "unisex",
        category: "Sunglasses",
        material: "acetate",
        color: "black",
        popularity: 88,
        createdAt: "2025-07-20",
        images: [
            "https://images.unsplash.com/photo-1558642472-5e11fc41c366?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1502877338535-766e1452684a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1516205651411-aef33a44f0c2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        ],
        description:
            "The legendary Persol 649, worn by style icons for generations. Supreme craftsmanship meets timeless design.",
        features: [
            "Crystal lenses",
            "Meflecto flexible stem system",
            "Hand-crafted in Italy",
            "Polarized options available",
        ],
    },
    {
        id: "p5",
        title: "Warby Parker Haskell",
        slug: "warby-parker-haskell",
        price: 145.0,
        gender: "unisex",
        category: "Prescription Glasses",
        material: "acetate",
        color: "crystal",
        popularity: 86,
        createdAt: "2025-09-05",
        images: [
            "https://images.unsplash.com/photo-1580144286105-7e4d82cbf14f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1597516193915-91e0c4683132?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1513185043877-1c37024c5a1a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        ],
        description:
            "Contemporary rectangular frames with a subtle twist. Perfect for both professional and casual settings.",
        features: [
            "Premium acetate frame",
            "Akulon-coated screws",
            "Anti-scratch coating",
            "Blue-light filtering available",
        ],
    },
    {
        id: "p6",
        title: "Maui Jim Red Sands",
        slug: "maui-jim-red-sands",
        price: 249.0,
        gender: "unisex",
        category: "Sunglasses",
        material: "titanium",
        color: "silver",
        popularity: 90,
        createdAt: "2025-08-30",
        images: [
            "https://images.unsplash.com/photo-1521737852567-6949f3f9f2b5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1526401485004-0e0e75c3b87b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        ],
        description:
            "Premium polarized sunglasses with PolarizedPlus2® technology for unmatched clarity and color enhancement.",
        features: [
            "PolarizedPlus2® lenses",
            "Titanium frame",
            "Waterproof coating",
            "Ultra-lightweight design",
        ],
    },
    {
        id: "p7",
        title: "Oliver Peoples Gregory Peck",
        slug: "oliver-peoples-gregory-peck",
        price: 389.0,
        gender: "men",
        category: "Prescription Glasses",
        material: "acetate",
        color: "dark tortoise",
        popularity: 94,
        createdAt: "2025-09-15",
        images: [
            "https://images.unsplash.com/photo-1555529669-4e5154390a27?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1548684486-ad3e8bba887e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1596410296373-3863f6b2df00?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        ],
        description:
            "Inspired by the glasses worn by Gregory Peck in 'To Kill a Mockingbird'. A perfect blend of vintage and contemporary.",
        features: [
            "Premium acetate frame",
            "Custom Oliver Peoples case",
            "Hand-laid hinges",
            "Progressive lens compatible",
        ],
    },
    {
        id: "p8",
        title: "Dior So Real",
        slug: "dior-so-real",
        price: 495.0,
        gender: "women",
        category: "Sunglasses",
        material: "metal",
        color: "rose gold",
        popularity: 96,
        createdAt: "2025-09-20",
        images: [
            "https://images.unsplash.com/photo-1526178652270-1e4f6209c811?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1571771893090-b0ab0f3a8a47?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        ],
        description:
            "Avant-garde design meets luxury craftsmanship. These iconic split-bridge sunglasses make a bold statement.",
        features: [
            "Split-bridge design",
            "Mirrored lenses",
            "Metallic finish",
            "Leather case included",
        ],
    },
];
